name: halian
services:
  api:
    build:
      dockerfile: Dockerfile
    container_name: api
    restart: always
    env_file:
      - ".env.docker"
    environment:
      - TWELVE_DATA_API_KEY=${TWELVE_DATA_API_KEY}
    ports:
      - "8000:8000"
    networks:
      - halian
    depends_on:
      - db
    command: >
      bash -c "alembic upgrade head && uvicorn application.api.main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - halian

  celery:
    build: .
    container_name: celery_worker
    command: celery -A application.celery.main:celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    networks:
      - halian

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - halian

networks:
  halian:
    driver: bridge

volumes:
  db_data: {}
