"""Add timezone

Revision ID: 48b1629931f3
Revises: 74ee984bbbf1
Create Date: 2025-07-05 13:55:27.253448

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from collections.abc import Sequence
from sqlalchemy.dialects import postgresql
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "48b1629931f3"
down_revision: str | None = "74ee984bbbf1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_prices",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.drop_index("ix_stock_prices_timestamp", table_name="stock_prices")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_stock_prices_timestamp",
        "stock_prices",
        ["timestamp"],
        unique=False,
    )
    op.alter_column(
        "stock_prices",
        "timestamp",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
