"""Remove timezone

Revision ID: 74ee984bbbf1
Revises: ae3c857a975a
Create Date: 2025-07-05 13:21:18.134475

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from collections.abc import Sequence
from sqlalchemy.dialects import postgresql
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "74ee984bbbf1"
down_revision: str | None = "ae3c857a975a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_prices",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_prices",
        "timestamp",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
